<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="guimetamodel" nsURI="http://guimetamodel" nsPrefix="guimetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="GUI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainview" lowerBound="1"
        eType="#//MainView" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderview" lowerBound="1"
        eType="#//OrderView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listview" lowerBound="1"
        eType="#//ListView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infoview" lowerBound="1"
        eType="#//InfoView" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="createview" lowerBound="1"
        eType="#//CreateView" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderView" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfoView" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateView" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfoSingleView" eSuperTypes="#//InfoView"/>
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
