<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="applicabilitymodel" nsURI="http://applicabilitymodel/applicabilitymodel"
    nsPrefix="applicabilitymodel">
  <eClassifiers xsi:type="ecore:EClass" name="DecisionModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualitymodel" lowerBound="1"
        eType="ecore:EClass ../../co.edu.icesi.shift.qaconfig/metamodels/QAsConfig.ecore#//RootQA"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentSetsModel" lowerBound="1"
        eType="ecore:EClass ../../co.edu.icesi.shift.componentsets/metamodels/ComponentSets.ecore#//ComponentSetsModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decisions" lowerBound="1"
        upperBound="-1" eType="#//Decision" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decision">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qaVariant" lowerBound="1"
        eType="ecore:EClass ../../co.edu.icesi.shift.qaconfig/metamodels/QAsConfig.ecore#//QA"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentSet" lowerBound="1"
        eType="ecore:EClass ../../co.edu.icesi.shift.componentsets/metamodels/ComponentSets.ecore#//ComponentSet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiresVariantSelected"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
</ecore:EPackage>
