package co.shift.pcs.web.ext.project;

import java.util.Date;

import co.shift.pcs.to.UserTO;
import co.shift.pcs.to.RiskTO;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;

public class ProjectForm extends CustomComponent {
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_1;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_3;
	
	@AutoGenerated
	private Button buttonManager;
	@AutoGenerated
	private TextField textFieldManager1;
	
	public TextField getTextFieldManager1() {
		return textFieldManager1;
	}
	
	@AutoGenerated
	private TextField textFieldManager2;
	
	public TextField getTextFieldManager2() {
		return textFieldManager2;
	}
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_4;
	
	@AutoGenerated
	private Button buttonPriorityRisk;
	@AutoGenerated
	private TextField textFieldPriorityRisk1;
	
	public TextField getTextFieldPriorityRisk1() {
		return textFieldPriorityRisk1;
	}
	
	@AutoGenerated
	private TextField textFieldPriorityRisk2;
	
	public TextField getTextFieldPriorityRisk2() {
		return textFieldPriorityRisk2;
	}
	
	@AutoGenerated
	private Button buttonDetailForm;

	@AutoGenerated
	private Button buttonRemoveDetail;

	@AutoGenerated
	private TabSheet tabSheet_1;
	
	public TabSheet getTabSheet_1() {
		return tabSheet_1;
	}

	@AutoGenerated
	private Label label_1;
	
	@AutoGenerated
	private Button buttonCreateProject;
	@AutoGenerated
	private Button buttonUpdateProject;
	@AutoGenerated
	private Button buttonDeleteProject;

	@AutoGenerated
	private TextField txtId;
	
	public TextField getTxtId() {
		return txtId;
	}
	@AutoGenerated
	private TextField txtDescription;
	
	public TextField getTxtDescription() {
		return txtDescription;
	}
	@AutoGenerated
	private TextField txtName;
	
	public TextField getTxtName() {
		return txtName;
	}
	@AutoGenerated
	private PopupDateField txtDStartDate;
	
	public PopupDateField getTxtDStartDate () {
		return txtDStartDate;
	}

	@AutoGenerated
	private Table table_1;
	
	public Table getTable_1() {
		return table_1;
	}
	
	@AutoGenerated
	private Table table_2;
	
	public Table getTable_2() {
		return table_2;
	}
	@AutoGenerated
	private Table table_3;
	
	public Table getTable_3() {
		return table_3;
	}
	
	public static final String ID = "ProjectForm";
	
	public ProjectForm() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		table_1.addContainerProperty("Id", Integer.class, null);
		table_1.addContainerProperty("Description", String.class, null);
		table_1.addContainerProperty("Name", String.class, null);
		table_1.addContainerProperty("StartDate", Date.class, null);
		table_1.setSelectable(true);
		table_1.setMultiSelect(false);
		table_1.setImmediate(true);
		
		table_1.addItemClickListener(new ItemClickListener() {

		@Override
		public void itemClick(ItemClickEvent event) {
			ProjectController.getInstance().listAllDetailsFromProject(
					event);
			}
		});
		table_2.addContainerProperty("Cc", String.class, null);
		table_2.addContainerProperty("Name", String.class, null);
		table_2.addContainerProperty("Cellphone", String.class, null);
		table_2.addContainerProperty("Password", String.class, null);
		table_2.setSelectable(true);
		table_2.setMultiSelect(false);
		table_2.setImmediate(true);
		
		tabSheet_1.addTab(table_2, "Users", null);
		table_3.addContainerProperty("Id", Integer.class, null);
		table_3.addContainerProperty("Description", String.class, null);
		table_3.addContainerProperty("Impact", Double.class, null);
		table_3.addContainerProperty("Name", String.class, null);
		table_3.addContainerProperty("Probability", Double.class, null);
		table_3.setSelectable(true);
		table_3.setMultiSelect(false);
		table_3.setImmediate(true);
		
		tabSheet_1.addTab(table_3, "Risks", null);
		
		buttonCreateProject.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				ProjectController.getInstance().createProject();
			}
		});
		buttonUpdateProject.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				ProjectController.getInstance().updateProject();
			}
		});
		buttonDeleteProject.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				ProjectController.getInstance().deleteProject();
			}
		});
		
		textFieldManager1.setEnabled(false);
		textFieldManager2.setEnabled(false);
		
		buttonManager.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				ProjectController.getInstance().popUpManagerForm();
			}
		});
		textFieldPriorityRisk1.setEnabled(false);
		textFieldPriorityRisk2.setEnabled(false);
		
		buttonPriorityRisk.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				ProjectController.getInstance().popUpPriorityRiskForm();
			}
		});
		
		buttonDetailForm.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				ProjectController.getInstance().popUpAddDetailForm();
			}
		});

		buttonRemoveDetail.addClickListener(new ClickListener() {

			@Override
			public void buttonClick(ClickEvent event) {
				ProjectController.getInstance().removeDetailRecord();
			}
		});
	}
	
	public void clearFormFields() {
		txtId.setValue("");
		txtDescription.setValue("");
		txtName.setValue("");
		txtDStartDate.setValue(null);
	}
	
	public void clearManagerFields() {
		textFieldManager1.setValue("");
		textFieldManager2.setValue("");
	}
	
	public void updateManagerFields(UserTO manager) {
		textFieldManager1.setValue(""+manager.getCc());
		textFieldManager2.setValue(""+manager.getName());
	}
	public void clearPriorityRiskFields() {
		textFieldPriorityRisk1.setValue("");
		textFieldPriorityRisk2.setValue("");
	}
	
	public void updatePriorityRiskFields(RiskTO priorityrisk) {
		textFieldPriorityRisk1.setValue(""+priorityrisk.getId());
		textFieldPriorityRisk2.setValue(""+priorityrisk.getDescription());
	}
	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_1() {
		// common part: create layout
		absoluteLayout_1 = new AbsoluteLayout();
		absoluteLayout_1.setCaption("Project");
		absoluteLayout_1.setImmediate(false);
		absoluteLayout_1.setWidth("340px");
		absoluteLayout_1.setHeight("230px");
		
		// txtId
		txtId = new TextField();
		txtId.setCaption("Id");
		txtId.setImmediate(false);
		txtId.setWidth("175px");
		txtId.setHeight("-1px");
		txtId.setRequired(true);
		absoluteLayout_1.addComponent(txtId,
				"top:40px;left:0.0px;");
		// txtDescription
		txtDescription = new TextField();
		txtDescription.setCaption("Description");
		txtDescription.setImmediate(false);
		txtDescription.setWidth("175px");
		txtDescription.setHeight("-1px");
		txtDescription.setRequired(true);
		absoluteLayout_1.addComponent(txtDescription,
				"top:80px;left:0.0px;");
		// txtName
		txtName = new TextField();
		txtName.setCaption("Name");
		txtName.setImmediate(false);
		txtName.setWidth("175px");
		txtName.setHeight("-1px");
		txtName.setRequired(true);
		absoluteLayout_1.addComponent(txtName,
				"top:120px;left:0.0px;");
		// txtDStartDate
		txtDStartDate = new PopupDateField();
		txtDStartDate.setCaption("StartDate");
		txtDStartDate.setImmediate(false);
		txtDStartDate.setWidth("-1px");
		txtDStartDate.setHeight("-1px");
		txtDStartDate.setRequired(true);
		absoluteLayout_1.addComponent(txtDStartDate,
				"top:160px;left:0.0px;");
		
		buttonCreateProject = new Button();
		buttonCreateProject.setCaption("Add");
		buttonCreateProject.setImmediate(true);
		buttonCreateProject.setWidth("65px");
		buttonCreateProject.setHeight("-1px");
		absoluteLayout_1.addComponent(buttonCreateProject, "top:200px;left:0px;");
		buttonUpdateProject = new Button();
		buttonUpdateProject.setCaption("Update");
		buttonUpdateProject.setImmediate(true);
		buttonUpdateProject.setWidth("65px");
		buttonUpdateProject.setHeight("-1px");
		absoluteLayout_1.addComponent(buttonUpdateProject, "top:200px;left:72px;");
		buttonDeleteProject = new Button();
		buttonDeleteProject.setCaption("Delete");
		buttonDeleteProject.setImmediate(true);
		buttonDeleteProject.setWidth("65px");
		buttonDeleteProject.setHeight("-1px");
		absoluteLayout_1.addComponent(buttonDeleteProject, "top:200px;left:144px;");
		
		return absoluteLayout_1;
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1024px");
		mainLayout.setHeight("500px");
		
		// top-level component properties
		setWidth("1024px");
		setHeight("500px");
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("150px");
		table_1.setHeight("100.0%");
		mainLayout.addComponent(table_1,
				"top:18.0px;bottom:-18.0px;left:0.0px;");
				
		// absoluteLayout_1
		absoluteLayout_1 = buildAbsoluteLayout_1();
		mainLayout.addComponent(absoluteLayout_1, "top:17.0px;left:170.0px;");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("18px");
		label_1.setValue("Project");
		mainLayout.addComponent(label_1, "top:0.0px;left:36.0px;");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2, "top:255px;left:170.0px;");

		// absoluteLayout_3
		absoluteLayout_3 = buildAbsoluteLayout_3();
		mainLayout.addComponent(absoluteLayout_3, "top:17.0px;left:685px;");
		// absoluteLayout_4
		absoluteLayout_4 = buildAbsoluteLayout_4();
		mainLayout.addComponent(absoluteLayout_4, "top:17.0px;left:845px;");

		return mainLayout;
	}
	
	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setCaption("Details");
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("505px");
		absoluteLayout_2.setHeight("200px");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		absoluteLayout_2.addComponent(tabSheet_1, "top:2.0px;left:0.0px;");
		
		// buttonDetailForm
		buttonDetailForm = new Button();
		buttonDetailForm.setCaption("Add");
		buttonDetailForm.setImmediate(true);
		buttonDetailForm.setWidth("73px");
		buttonDetailForm.setHeight("-1px");
		absoluteLayout_2.addComponent(buttonDetailForm, "top:36.0px;left:419.0px;");

		// buttonRemoveDetail
		buttonRemoveDetail = new Button();
		buttonRemoveDetail.setCaption("Remove");
		buttonRemoveDetail.setImmediate(true);
		buttonRemoveDetail.setWidth("-1px");
		buttonRemoveDetail.setHeight("-1px");
		absoluteLayout_2.addComponent(buttonRemoveDetail, "top:65.0px;left:419.0px;");

		return absoluteLayout_2;
	}
	
	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("409px");
		tabSheet_1.setHeight("198px");
		
		// table_2
		table_2 = new Table();
		table_2.setImmediate(false);
		table_2.setWidth("409px");
		table_2.setHeight("-1px");
		// table_3
		table_3 = new Table();
		table_3.setImmediate(false);
		table_3.setWidth("409px");
		table_3.setHeight("-1px");

		return tabSheet_1;
	}
	
	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_3() {
		// common part: create layout
		absoluteLayout_3 = new AbsoluteLayout();
		absoluteLayout_3.setCaption("Manager");
		absoluteLayout_3.setImmediate(false);
		absoluteLayout_3.setWidth("150px");
		absoluteLayout_3.setHeight("150px");
		
		// textFieldManager1
		textFieldManager1 = new TextField();
		textFieldManager1.setCaption("Manager Cc");
		textFieldManager1.setImmediate(false);
		textFieldManager1.setWidth("-1px");
		textFieldManager1.setHeight("-1px");
		absoluteLayout_3.addComponent(textFieldManager1, "top:22.0px;left:7.0px;");
		
		// textFieldManager2
		textFieldManager2 = new TextField();
		textFieldManager2.setCaption("Manager Name");
		textFieldManager2.setImmediate(false);
		textFieldManager2.setWidth("-1px");
		textFieldManager2.setHeight("-1px");
		absoluteLayout_3.addComponent(textFieldManager2, "top:61.0px;left:7.0px;");
		
		// buttonManager
		buttonManager = new Button();
		buttonManager.setCaption("Set Manager");
		buttonManager.setImmediate(true);
		buttonManager.setWidth("-1px");
		buttonManager.setHeight("-1px");
		absoluteLayout_3.addComponent(buttonManager, "top:93.0px;left:24.0px;");
		
		return absoluteLayout_3;
	}
	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_4() {
		// common part: create layout
		absoluteLayout_4 = new AbsoluteLayout();
		absoluteLayout_4.setCaption("PriorityRisk");
		absoluteLayout_4.setImmediate(false);
		absoluteLayout_4.setWidth("150px");
		absoluteLayout_4.setHeight("150px");
		
		// textFieldPriorityRisk1
		textFieldPriorityRisk1 = new TextField();
		textFieldPriorityRisk1.setCaption("PriorityRisk Id");
		textFieldPriorityRisk1.setImmediate(false);
		textFieldPriorityRisk1.setWidth("-1px");
		textFieldPriorityRisk1.setHeight("-1px");
		absoluteLayout_4.addComponent(textFieldPriorityRisk1, "top:22.0px;left:7.0px;");
		
		// textFieldPriorityRisk2
		textFieldPriorityRisk2 = new TextField();
		textFieldPriorityRisk2.setCaption("PriorityRisk Description");
		textFieldPriorityRisk2.setImmediate(false);
		textFieldPriorityRisk2.setWidth("-1px");
		textFieldPriorityRisk2.setHeight("-1px");
		absoluteLayout_4.addComponent(textFieldPriorityRisk2, "top:61.0px;left:7.0px;");
		
		// buttonPriorityRisk
		buttonPriorityRisk = new Button();
		buttonPriorityRisk.setCaption("Set PriorityRisk");
		buttonPriorityRisk.setImmediate(true);
		buttonPriorityRisk.setWidth("-1px");
		buttonPriorityRisk.setHeight("-1px");
		absoluteLayout_4.addComponent(buttonPriorityRisk, "top:93.0px;left:24.0px;");
		
		return absoluteLayout_4;
	}
}
