package co.shift.templates.ejb.basic;

import co.shift.generators.domain.DomainCodeGenerator;
import com.google.common.base.Objects;
import domainmetamodel.Association;
import domainmetamodel.Attribute;
import domainmetamodel.BusinessEntity;
import domainmetamodel.DataType;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class DAOImplTemplate {
  public static CharSequence generate(final BusinessEntity be, final String packageName, final List<Association> associations) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package co.shift.");
    String _lowerCase = packageName.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".");
    String _name = be.getName();
    String _lowerCase_1 = _name.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append(".control;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.ArrayList;");
    _builder.newLine();
    _builder.append("import java.util.Date;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import javax.ejb.EJB;");
    _builder.newLine();
    _builder.append("import javax.ejb.Stateless;");
    _builder.newLine();
    _builder.append("import javax.persistence.EntityManager;");
    _builder.newLine();
    _builder.append("import javax.persistence.NoResultException;");
    _builder.newLine();
    _builder.append("import javax.persistence.PersistenceContext;");
    _builder.newLine();
    _builder.append("import javax.persistence.Query;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import co.shift.");
    String _lowerCase_2 = packageName.toLowerCase();
    _builder.append(_lowerCase_2, "");
    _builder.append(".to.");
    String _name_1 = be.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper, "");
    _builder.append("TO;");
    _builder.newLineIfNotEmpty();
    String _name_2 = be.getName();
    String _extendContribution = DomainCodeGenerator.extendContribution("_r_2_10", DomainCodeGenerator.CONTRIBUTE_TO_IMPORT, packageName, _name_2);
    _builder.append(_extendContribution, "");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("@Stateless");
    _builder.newLine();
    _builder.append("public class ");
    String _name_3 = be.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_3);
    _builder.append(_firstUpper_1, "");
    _builder.append("DAO implements I");
    String _name_4 = be.getName();
    String _firstUpper_2 = StringExtensions.toFirstUpper(_name_4);
    _builder.append(_firstUpper_2, "");
    _builder.append("DAO {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@PersistenceContext(unitName = \"co.shift.pcs.");
    String _name_5 = be.getName();
    String _lowerCase_3 = _name_5.toLowerCase();
    _builder.append(_lowerCase_3, "\t");
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private EntityManager em;");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    final String attribute2 = DomainCodeGenerator.extendContribution("_r_2_10", DomainCodeGenerator.CONTRIBUTE_TO_ATTRIBUTE);
    _builder.newLineIfNotEmpty();
    {
      boolean _and = false;
      boolean _notEquals = (!Objects.equal(attribute2, null));
      if (!_notEquals) {
        _and = false;
      } else {
        boolean _equals = attribute2.equals("");
        boolean _not = (!_equals);
        _and = _not;
      }
      if (_and) {
        _builder.append("\t");
        _builder.append(attribute2, "\t");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    {
      List<Association> _detailSimpleAssociations = DomainCodeGenerator.getDetailSimpleAssociations(be, associations);
      for(final Association association : _detailSimpleAssociations) {
        _builder.append("\t");
        EObject _eContainer = association.eContainer();
        final BusinessEntity container = ((BusinessEntity) _eContainer);
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        Attribute _iD = DomainCodeGenerator.getID(container);
        DataType _dataType = _iD.getDataType();
        final String type = _dataType.getLiteral();
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("public ");
        String _name_6 = be.getName();
        _builder.append(_name_6, "\t");
        _builder.append("TO get");
        String _name_7 = container.getName();
        String _firstUpper_3 = StringExtensions.toFirstUpper(_name_7);
        _builder.append(_firstUpper_3, "\t");
        String _name_8 = association.getName();
        String _firstUpper_4 = StringExtensions.toFirstUpper(_name_8);
        _builder.append(_firstUpper_4, "\t");
        _builder.append("(");
        String _type = DomainCodeGenerator.getType(type);
        _builder.append(_type, "\t");
        _builder.append(" ");
        String _name_9 = container.getName();
        String _lowerCase_4 = _name_9.toLowerCase();
        _builder.append(_lowerCase_4, "\t");
        Attribute _iD_1 = DomainCodeGenerator.getID(container);
        String _name_10 = _iD_1.getName();
        String _firstUpper_5 = StringExtensions.toFirstUpper(_name_10);
        _builder.append(_firstUpper_5, "\t");
        _builder.append("){");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("Query query = em");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append(".createNativeQuery(\"SELECT u.* FROM ");
        String _name_11 = be.getName();
        String _firstUpper_6 = StringExtensions.toFirstUpper(_name_11);
        _builder.append(_firstUpper_6, "\t\t");
        _builder.append(" u, ");
        String _name_12 = container.getName();
        String _firstUpper_7 = StringExtensions.toFirstUpper(_name_12);
        _builder.append(_firstUpper_7, "\t\t");
        _builder.append(" p WHERE p.");
        String _name_13 = association.getName();
        String _lowerCase_5 = _name_13.toLowerCase();
        _builder.append(_lowerCase_5, "\t\t");
        _builder.append(" = u.");
        Attribute _iD_2 = DomainCodeGenerator.getID(be);
        String _name_14 = _iD_2.getName();
        String _lowerCase_6 = _name_14.toLowerCase();
        _builder.append(_lowerCase_6, "\t\t");
        _builder.append(" AND p.");
        Attribute _iD_3 = DomainCodeGenerator.getID(container);
        String _name_15 = _iD_3.getName();
        String _lowerCase_7 = _name_15.toLowerCase();
        _builder.append(_lowerCase_7, "\t\t");
        _builder.append(" = \"");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t\t\t");
        _builder.append("+ ");
        String _name_16 = container.getName();
        String _lowerCase_8 = _name_16.toLowerCase();
        _builder.append(_lowerCase_8, "\t\t\t\t");
        Attribute _iD_4 = DomainCodeGenerator.getID(container);
        String _name_17 = _iD_4.getName();
        String _firstUpper_8 = StringExtensions.toFirstUpper(_name_17);
        _builder.append(_firstUpper_8, "\t\t\t\t");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("try {");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("Object[] ");
        String _name_18 = association.getName();
        String _lowerCase_9 = _name_18.toLowerCase();
        _builder.append(_lowerCase_9, "\t\t\t");
        _builder.append(" = (Object[]) query.getSingleResult();");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t\t");
        String _name_19 = be.getName();
        String _firstUpper_9 = StringExtensions.toFirstUpper(_name_19);
        _builder.append(_firstUpper_9, "\t\t\t");
        _builder.append("TO u = new ");
        String _name_20 = be.getName();
        String _firstUpper_10 = StringExtensions.toFirstUpper(_name_20);
        _builder.append(_firstUpper_10, "\t\t\t");
        _builder.append("TO();");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t\t");
        int i = 0;
        _builder.newLineIfNotEmpty();
        {
          EList<Attribute> _attributes = be.getAttributes();
          for(final Attribute attribute : _attributes) {
            _builder.append("\t");
            _builder.append("\t\t");
            String _type_1 = DomainCodeGenerator.getType(attribute);
            _builder.append(_type_1, "\t\t\t");
            _builder.append(" t");
            String _name_21 = attribute.getName();
            String _firstUpper_11 = StringExtensions.toFirstUpper(_name_21);
            _builder.append(_firstUpper_11, "\t\t\t");
            _builder.append(" = (");
            String _type_2 = DomainCodeGenerator.getType(attribute);
            _builder.append(_type_2, "\t\t\t");
            _builder.append(") ");
            String _name_22 = association.getName();
            String _lowerCase_10 = _name_22.toLowerCase();
            _builder.append(_lowerCase_10, "\t\t\t");
            _builder.append("[");
            _builder.append(i, "\t\t\t");
            _builder.append("];");
            _builder.newLineIfNotEmpty();
            _builder.append("\t");
            _builder.append("\t\t");
            int c = i++;
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("\t");
        _builder.append("\t\t");
        String _extendContribution_1 = DomainCodeGenerator.extendContribution("_r_2_10", DomainCodeGenerator.CONTRIBUTE_TO_BIMPL, null, be, null, null, null, null, null, Integer.valueOf(3));
        _builder.append(_extendContribution_1, "\t\t\t");
        _builder.newLineIfNotEmpty();
        {
          EList<Attribute> _attributes_1 = be.getAttributes();
          for(final Attribute attribute_1 : _attributes_1) {
            _builder.append("\t");
            _builder.append("\t\t");
            _builder.append("u.set");
            String _name_23 = attribute_1.getName();
            String _firstUpper_12 = StringExtensions.toFirstUpper(_name_23);
            _builder.append(_firstUpper_12, "\t\t\t");
            _builder.append("(t");
            String _name_24 = attribute_1.getName();
            String _firstUpper_13 = StringExtensions.toFirstUpper(_name_24);
            _builder.append(_firstUpper_13, "\t\t\t");
            _builder.append(");");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("return u;");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("} catch (NoResultException e) {");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("return null;");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.append("\t");
    _builder.newLine();
    {
      List<Association> _detailMultipleAssociations = DomainCodeGenerator.getDetailMultipleAssociations(be, associations);
      for(final Association association_1 : _detailMultipleAssociations) {
        _builder.append("\t");
        EObject _eContainer_1 = association_1.eContainer();
        final BusinessEntity container_1 = ((BusinessEntity) _eContainer_1);
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        Attribute _iD_5 = DomainCodeGenerator.getID(container_1);
        DataType _dataType_1 = _iD_5.getDataType();
        final String type_1 = _dataType_1.getLiteral();
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("public List<");
        String _name_25 = be.getName();
        String _firstUpper_14 = StringExtensions.toFirstUpper(_name_25);
        _builder.append(_firstUpper_14, "\t");
        _builder.append("TO> get");
        String _name_26 = be.getName();
        String _firstUpper_15 = StringExtensions.toFirstUpper(_name_26);
        _builder.append(_firstUpper_15, "\t");
        _builder.append("From");
        String _name_27 = container_1.getName();
        String _firstUpper_16 = StringExtensions.toFirstUpper(_name_27);
        _builder.append(_firstUpper_16, "\t");
        _builder.append("(");
        String _type_3 = DomainCodeGenerator.getType(type_1);
        _builder.append(_type_3, "\t");
        _builder.append(" ");
        String _name_28 = container_1.getName();
        String _lowerCase_11 = _name_28.toLowerCase();
        _builder.append(_lowerCase_11, "\t");
        Attribute _iD_6 = DomainCodeGenerator.getID(container_1);
        String _name_29 = _iD_6.getName();
        String _firstUpper_17 = StringExtensions.toFirstUpper(_name_29);
        _builder.append(_firstUpper_17, "\t");
        _builder.append("){");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("List<");
        String _name_30 = be.getName();
        String _firstUpper_18 = StringExtensions.toFirstUpper(_name_30);
        _builder.append(_firstUpper_18, "\t\t");
        _builder.append("TO> ");
        String _name_31 = be.getName();
        String _lowerCase_12 = _name_31.toLowerCase();
        _builder.append(_lowerCase_12, "\t\t");
        _builder.append("s = new ArrayList<>();");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("Query query = em");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t\t\t");
        _builder.append(".createNativeQuery(\"SELECT u.* FROM ");
        String _name_32 = be.getName();
        String _firstUpper_19 = StringExtensions.toFirstUpper(_name_32);
        _builder.append(_firstUpper_19, "\t\t\t\t");
        _builder.append(" u, ");
        String _name_33 = container_1.getName();
        String _firstUpper_20 = StringExtensions.toFirstUpper(_name_33);
        _builder.append(_firstUpper_20, "\t\t\t\t");
        String _name_34 = be.getName();
        String _firstUpper_21 = StringExtensions.toFirstUpper(_name_34);
        _builder.append(_firstUpper_21, "\t\t\t\t");
        _builder.append(" pu WHERE u.");
        Attribute _iD_7 = DomainCodeGenerator.getID(be);
        String _name_35 = _iD_7.getName();
        String _lowerCase_13 = _name_35.toLowerCase();
        _builder.append(_lowerCase_13, "\t\t\t\t");
        _builder.append(" = pu.");
        String _name_36 = be.getName();
        String _lowerCase_14 = _name_36.toLowerCase();
        _builder.append(_lowerCase_14, "\t\t\t\t");
        _builder.append(" AND pu.");
        String _name_37 = container_1.getName();
        String _lowerCase_15 = _name_37.toLowerCase();
        _builder.append(_lowerCase_15, "\t\t\t\t");
        _builder.append(" = \"");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t\t\t\t\t");
        _builder.append("+ ");
        String _name_38 = container_1.getName();
        String _lowerCase_16 = _name_38.toLowerCase();
        _builder.append(_lowerCase_16, "\t\t\t\t\t\t");
        Attribute _iD_8 = DomainCodeGenerator.getID(container_1);
        String _name_39 = _iD_8.getName();
        String _firstUpper_22 = StringExtensions.toFirstUpper(_name_39);
        _builder.append(_firstUpper_22, "\t\t\t\t\t\t");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("List<Object[]> found");
        String _name_40 = be.getName();
        String _firstUpper_23 = StringExtensions.toFirstUpper(_name_40);
        _builder.append(_firstUpper_23, "\t\t");
        _builder.append("s = query.getResultList();");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        String _name_41 = be.getName();
        String _firstUpper_24 = StringExtensions.toFirstUpper(_name_41);
        _builder.append(_firstUpper_24, "\t\t");
        _builder.append("TO u = null;");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("for (Object[] ");
        String _name_42 = be.getName();
        String _lowerCase_17 = _name_42.toLowerCase();
        _builder.append(_lowerCase_17, "\t\t");
        _builder.append(" : found");
        String _name_43 = be.getName();
        String _firstUpper_25 = StringExtensions.toFirstUpper(_name_43);
        _builder.append(_firstUpper_25, "\t\t");
        _builder.append("s) {");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t\t");
        _builder.append("u = new ");
        String _name_44 = be.getName();
        String _firstUpper_26 = StringExtensions.toFirstUpper(_name_44);
        _builder.append(_firstUpper_26, "\t\t\t");
        _builder.append("TO();");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t\t");
        int i_1 = 0;
        _builder.newLineIfNotEmpty();
        {
          EList<Attribute> _attributes_2 = be.getAttributes();
          for(final Attribute attribute_2 : _attributes_2) {
            _builder.append("\t");
            _builder.append("\t\t");
            String _type_4 = DomainCodeGenerator.getType(attribute_2);
            _builder.append(_type_4, "\t\t\t");
            _builder.append(" t");
            String _name_45 = attribute_2.getName();
            String _firstUpper_27 = StringExtensions.toFirstUpper(_name_45);
            _builder.append(_firstUpper_27, "\t\t\t");
            _builder.append(" = (");
            String _type_5 = DomainCodeGenerator.getType(attribute_2);
            _builder.append(_type_5, "\t\t\t");
            _builder.append(") ");
            String _name_46 = be.getName();
            String _lowerCase_18 = _name_46.toLowerCase();
            _builder.append(_lowerCase_18, "\t\t\t");
            _builder.append("[");
            _builder.append(i_1, "\t\t\t");
            _builder.append("];");
            _builder.newLineIfNotEmpty();
            _builder.append("\t");
            _builder.append("\t\t");
            int c_1 = i_1++;
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("\t");
        _builder.append("\t\t");
        String _extendContribution_2 = DomainCodeGenerator.extendContribution("_r_2_10", DomainCodeGenerator.CONTRIBUTE_TO_BIMPL, null, be, null, null, null, null, null, Integer.valueOf(3));
        _builder.append(_extendContribution_2, "\t\t\t");
        _builder.newLineIfNotEmpty();
        {
          EList<Attribute> _attributes_3 = be.getAttributes();
          for(final Attribute attribute_3 : _attributes_3) {
            _builder.append("\t");
            _builder.append("\t\t");
            _builder.append("u.set");
            String _name_47 = attribute_3.getName();
            String _firstUpper_28 = StringExtensions.toFirstUpper(_name_47);
            _builder.append(_firstUpper_28, "\t\t\t");
            _builder.append("(t");
            String _name_48 = attribute_3.getName();
            String _firstUpper_29 = StringExtensions.toFirstUpper(_name_48);
            _builder.append(_firstUpper_29, "\t\t\t");
            _builder.append(");");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("\t");
        _builder.append("\t\t");
        String _name_49 = be.getName();
        String _lowerCase_19 = _name_49.toLowerCase();
        _builder.append(_lowerCase_19, "\t\t\t");
        _builder.append("s.add(u);");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("return ");
        String _name_50 = be.getName();
        String _lowerCase_20 = _name_50.toLowerCase();
        _builder.append(_lowerCase_20, "\t\t");
        _builder.append("s;");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
      }
    }
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
