package co.shift.templates.ejb.basic;

import domainmetamodel.Association;
import domainmetamodel.BusinessEntity;
import java.util.List;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class JPAPKEncapTemplate {
  public static CharSequence generate(final BusinessEntity be, final String packageName, final String className, final List<Association> associations, final IFileSystemAccess fsa) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package co.shift.");
    String _lowerCase = packageName.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".");
    String _name = be.getName();
    String _lowerCase_1 = _name.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append(".entity;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.io.Serializable;");
    _builder.newLine();
    _builder.append("import javax.persistence.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Entity");
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(className, "");
    _builder.append(" implements Serializable {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static final long serialVersionUID = 1L;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@EmbeddedId");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private ");
    _builder.append(className, "\t");
    _builder.append("PK id;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@ManyToOne");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JoinColumn(name=\"");
    String _name_1 = be.getName();
    String _lowerCase_2 = _name_1.toLowerCase();
    _builder.append(_lowerCase_2, "\t");
    _builder.append("\", insertable=false, updatable=false)");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private ");
    String _name_2 = be.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name_2);
    _builder.append(_firstUpper, "\t");
    _builder.append(" ");
    String _name_3 = be.getName();
    String _lowerCase_3 = _name_3.toLowerCase();
    _builder.append(_lowerCase_3, "\t");
    _builder.append("Bean;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(className, "\t");
    _builder.append("() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    _builder.append(className, "\t");
    _builder.append("PK getId() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return this.id;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setId(");
    _builder.append(className, "\t");
    _builder.append("PK id) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this.id = id;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    String _name_4 = be.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_4);
    _builder.append(_firstUpper_1, "\t");
    _builder.append(" get");
    String _name_5 = be.getName();
    String _firstUpper_2 = StringExtensions.toFirstUpper(_name_5);
    _builder.append(_firstUpper_2, "\t");
    _builder.append("Bean() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return this.");
    String _name_6 = be.getName();
    String _lowerCase_4 = _name_6.toLowerCase();
    _builder.append(_lowerCase_4, "\t\t");
    _builder.append("Bean;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void set");
    String _name_7 = be.getName();
    String _firstUpper_3 = StringExtensions.toFirstUpper(_name_7);
    _builder.append(_firstUpper_3, "\t");
    _builder.append("Bean(");
    String _name_8 = be.getName();
    String _firstUpper_4 = StringExtensions.toFirstUpper(_name_8);
    _builder.append(_firstUpper_4, "\t");
    _builder.append(" ");
    String _name_9 = be.getName();
    String _lowerCase_5 = _name_9.toLowerCase();
    _builder.append(_lowerCase_5, "\t");
    _builder.append("Bean) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this.");
    String _name_10 = be.getName();
    String _lowerCase_6 = _name_10.toLowerCase();
    _builder.append(_lowerCase_6, "\t\t");
    _builder.append("Bean = ");
    String _name_11 = be.getName();
    String _lowerCase_7 = _name_11.toLowerCase();
    _builder.append(_lowerCase_7, "\t\t");
    _builder.append("Bean;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
