package co.shift.templates.web.contributed.authenticity;

import domainmetamodel.BusinessEntity;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class LoginControllerTemplate {
  public static CharSequence generate(final String packageName, final BusinessEntity authEntity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package co.shift.");
    String _lowerCase = packageName.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".web.ext.authenticator;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import co.shift.");
    String _lowerCase_1 = packageName.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append(".web.AbstractController;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_2 = packageName.toLowerCase();
    _builder.append(_lowerCase_2, "");
    _builder.append(".web.");
    String _upperCase = packageName.toUpperCase();
    _builder.append(_upperCase, "");
    _builder.append("UI;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_3 = packageName.toLowerCase();
    _builder.append(_lowerCase_3, "");
    _builder.append(".web.Registry;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_4 = packageName.toLowerCase();
    _builder.append(_lowerCase_4, "");
    _builder.append(".web.client.ContentPanel;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_5 = packageName.toLowerCase();
    _builder.append(_lowerCase_5, "");
    _builder.append(".web.client.MenuPanel;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_6 = packageName.toLowerCase();
    _builder.append(_lowerCase_6, "");
    _builder.append(".to.");
    String _name = authEntity.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "");
    _builder.append("TO;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_7 = packageName.toLowerCase();
    _builder.append(_lowerCase_7, "");
    _builder.append(".");
    String _name_1 = authEntity.getName();
    String _lowerCase_8 = _name_1.toLowerCase();
    _builder.append(_lowerCase_8, "");
    _builder.append(".boundary.I");
    String _name_2 = authEntity.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_2);
    _builder.append(_firstUpper_1, "");
    _builder.append("Manager;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_9 = packageName.toLowerCase();
    _builder.append(_lowerCase_9, "");
    _builder.append(".util.beanlocator.BeanLocator;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public class LoginController extends AbstractController{");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static LoginController controller;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private I");
    String _name_3 = authEntity.getName();
    String _firstUpper_2 = StringExtensions.toFirstUpper(_name_3);
    _builder.append(_firstUpper_2, "\t");
    _builder.append("Manager ");
    String _name_4 = authEntity.getName();
    String _lowerCase_10 = _name_4.toLowerCase();
    _builder.append(_lowerCase_10, "\t");
    _builder.append("Manager;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private LoginController() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("doLookup();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private void doLookup() {");
    _builder.newLine();
    _builder.append("\t\t");
    String _name_5 = authEntity.getName();
    String _lowerCase_11 = _name_5.toLowerCase();
    _builder.append(_lowerCase_11, "\t\t");
    _builder.append("Manager = BeanLocator.lookup(");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append("I");
    String _name_6 = authEntity.getName();
    String _firstUpper_3 = StringExtensions.toFirstUpper(_name_6);
    _builder.append(_firstUpper_3, "\t\t\t\t");
    _builder.append("Manager.class,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append("new BeanLocator().getGlobalJNDIName()");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".withAppName(\"co.shift.ear\")");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".withModuleName(\"co.shift.ejb\")");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".withBeanName(\"");
    String _name_7 = authEntity.getName();
    String _firstUpper_4 = StringExtensions.toFirstUpper(_name_7);
    _builder.append(_firstUpper_4, "\t\t\t\t\t\t");
    _builder.append("Manager\")");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".withBusinessInterface(I");
    String _name_8 = authEntity.getName();
    String _firstUpper_5 = StringExtensions.toFirstUpper(_name_8);
    _builder.append(_firstUpper_5, "\t\t\t\t\t\t");
    _builder.append("Manager.class).asString());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static LoginController getInstance() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (controller == null) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("controller = new LoginController();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("LoginForm uF = new LoginForm();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Registry.register(LoginForm.ID, uF);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return controller;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void showLoginForm() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("LoginForm loginForm = Registry.get(LoginForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ContentPanel panel = Registry.get(");
    String _upperCase_1 = packageName.toUpperCase();
    _builder.append(_upperCase_1, "\t\t");
    _builder.append("UI.CONTENT_PANEL);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("panel.removeContent();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("panel.setContent(loginForm);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void authenticate() {");
    _builder.newLine();
    _builder.append("\t\t");
    String _upperCase_2 = packageName.toUpperCase();
    _builder.append(_upperCase_2, "\t\t");
    _builder.append("UI ui = Registry.get(");
    String _upperCase_3 = packageName.toUpperCase();
    _builder.append(_upperCase_3, "\t\t");
    _builder.append("UI.UI);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("LoginForm lF = Registry.get(LoginForm.ID);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("String userID = lF.getTextField_1().getValue();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("String password = lF.getPasswordField_1().getValue();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (userID != null && !userID.equals(\"\") && password != null");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("&& !password.equals(\"\")) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("UserTO user = userManager.authenticate(userID, password);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("Registry.register(");
    String _upperCase_4 = packageName.toUpperCase();
    _builder.append(_upperCase_4, "\t\t\t\t");
    _builder.append("UI.USER, user);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append("if (user != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("MenuPanel menu = Registry.get(");
    String _upperCase_5 = packageName.toUpperCase();
    _builder.append(_upperCase_5, "\t\t\t\t\t");
    _builder.append("UI.MENU_PANEL);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("extendUI(menu, null);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_6 = packageName.toUpperCase();
    _builder.append(_upperCase_6, "\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("\"Please fill in all required fields (*)\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_7 = packageName.toUpperCase();
    _builder.append(_upperCase_7, "\t\t\t");
    _builder.append("UI.MSG_ERR, e.getMessage());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
