cd /Users/daviddurangiraldo/Desktop/
/Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/rootProject.sh < /Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/rootProjectInput.txt
cd /Users/daviddurangiraldo/Desktop/co.shift.root/
/Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/vaadinProject.sh < /Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/vaadinProjectInput.txt
/Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/ejbProject.sh < /Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/ejbProjectInput.txt
/Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/ejbCProject.sh < /Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/ejbProjectCInput.txt
/Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/earProject.sh < /Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/earProjectInput.txt
/Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/prjejbProject.sh < /Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/prjejbProjectInput.txt
/Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/prjsecurity.sh < /Users/daviddurangiraldo/Dropbox/JulianC/Maestria/201502/FabricasDeSoftware/152/runtime-EclipseApplication/../workspace/co.edu.icesi.shift.generator/files/prjsecurityInput.txt
killall Terminal