package co.shift.templates.web.basic;

import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class UITemplate {
  public static CharSequence generate(final String packageName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package co.shift.");
    String _lowerCase = packageName.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".web;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import co.shift.");
    String _lowerCase_1 = packageName.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append(".web.client.ContentPanel;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_2 = packageName.toLowerCase();
    _builder.append(_lowerCase_2, "");
    _builder.append(".web.client.MenuPanel;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import com.vaadin.server.VaadinRequest;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.Component;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.Notification.Type;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.Notification;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.UI;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.VerticalLayout;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.Window;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("/**");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("* Main UI class");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("@SuppressWarnings(\"serial\")");
    _builder.newLine();
    _builder.append("public class ");
    String _upperCase = packageName.toUpperCase();
    _builder.append(_upperCase, "");
    _builder.append("UI extends UI {");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String UI = \"UI\";");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String USER = \"USER\";");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String USER_SERVICES = \"USER_SERVICES\";");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String MSG_NOT = \"Notification\";");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String MSG_ERR = \"Error\";");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String MENU_PANEL = \"MenuPanel\";");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String CONTENT_PANEL = \"ContentPanel\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Window subWindow;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("protected void init(VaadinRequest request) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("final VerticalLayout layout = new VerticalLayout();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("layout.setMargin(true);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("layout.setSpacing(true);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Menu Panel");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("MenuPanel menuPanel = new MenuPanel();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("layout.addComponent(menuPanel);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Registry.register(MENU_PANEL, menuPanel);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// Content Panel");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ContentPanel contentPanel = new ContentPanel();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("contentPanel.setImmediate(true);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("layout.addComponent(contentPanel);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Registry.register(CONTENT_PANEL, contentPanel);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("setContent(layout);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("// SubWindow");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("subWindow = new Window();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("VerticalLayout subContent = new VerticalLayout();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("subContent.setMargin(true);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("subWindow.setContent(subContent);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Registry.register(UI, this);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("UIController.getInstance();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void showNotification(String title, String message) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Notification.show(title, message, Type.TRAY_NOTIFICATION);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void openSubWindow(String caption, Component component) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("subWindow.setCaption(caption);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("VerticalLayout subContent = (VerticalLayout) subWindow.getContent();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("subContent.removeAllComponents();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("subContent.addComponent(component);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("subWindow.center();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("addWindow(subWindow);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void closeSubWindow() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("removeWindow(subWindow);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
