package co.shift.templates.web.contributed.authenticity;

import co.shift.generators.domain.DomainCodeUtilities;
import domainmetamodel.Attribute;
import domainmetamodel.BusinessEntity;
import domainmetamodel.Contracts;
import domainmetamodel.ListAll;
import java.util.List;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class AuthorizerControllerTemplate {
  public static CharSequence generate(final String packageName, final BusinessEntity authEntity) {
    StringConcatenation _builder = new StringConcatenation();
    Attribute beId = DomainCodeUtilities.getID(authEntity);
    _builder.newLineIfNotEmpty();
    _builder.append("package co.shift.");
    String _lowerCase = packageName.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".web.ext.authorizer;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import com.vaadin.ui.ComboBox;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.TabSheet;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.TextField;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.MenuBar.Command;");
    _builder.newLine();
    _builder.append("import com.vaadin.ui.MenuBar.MenuItem;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import co.shift.");
    String _lowerCase_1 = packageName.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append(".web.ext.");
    String _name = authEntity.getName();
    String _lowerCase_2 = _name.toLowerCase();
    _builder.append(_lowerCase_2, "");
    _builder.append(".");
    String _name_1 = authEntity.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper, "");
    _builder.append("Controller;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_3 = packageName.toLowerCase();
    _builder.append(_lowerCase_3, "");
    _builder.append(".web.");
    String _upperCase = packageName.toUpperCase();
    _builder.append(_upperCase, "");
    _builder.append("UI;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_4 = packageName.toLowerCase();
    _builder.append(_lowerCase_4, "");
    _builder.append(".web.ProcessContributor;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_5 = packageName.toLowerCase();
    _builder.append(_lowerCase_5, "");
    _builder.append(".web.Registry;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_6 = packageName.toLowerCase();
    _builder.append(_lowerCase_6, "");
    _builder.append(".web.client.ContentPanel;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_7 = packageName.toLowerCase();
    _builder.append(_lowerCase_7, "");
    _builder.append(".to.RoleTO;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_8 = packageName.toLowerCase();
    _builder.append(_lowerCase_8, "");
    _builder.append(".to.ServiceTO;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_9 = packageName.toLowerCase();
    _builder.append(_lowerCase_9, "");
    _builder.append(".to.");
    String _name_2 = authEntity.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_2);
    _builder.append(_firstUpper_1, "");
    _builder.append("TO;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_10 = packageName.toLowerCase();
    _builder.append(_lowerCase_10, "");
    _builder.append(".util.beanlocator.BeanLocator;");
    _builder.newLineIfNotEmpty();
    _builder.append("import co.shift.");
    String _lowerCase_11 = packageName.toLowerCase();
    _builder.append(_lowerCase_11, "");
    _builder.append(".authorization.boundary.IAuthorizationManager;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("public class AuthorizerController implements ProcessContributor {");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static AuthorizerController controller;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private IAuthorizationManager authManager;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static final int TAB_");
    String _name_3 = authEntity.getName();
    String _upperCase_1 = _name_3.toUpperCase();
    _builder.append(_upperCase_1, "\t");
    _builder.append("S = 0;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private static final int TAB_ROLES = 1;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static final String ID = \"AuthorizerController\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private AuthorizerController() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("doLookup();");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private void doLookup() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("authManager = BeanLocator.lookup(");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("IAuthorizationManager.class,");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("new BeanLocator().getGlobalJNDIName()");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".withAppName(\"co.shift.ear\")");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".withModuleName(\"co.shift.ejb\")");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".withBeanName(\"AuthorizationManager\")");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".withBusinessInterface(IAuthorizationManager.class)");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".asString());");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void showAuthForm() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm authForm = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ContentPanel panel = Registry.get(");
    String _upperCase_2 = packageName.toUpperCase();
    _builder.append(_upperCase_2, "\t\t");
    _builder.append("UI.CONTENT_PANEL);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("listAll");
    String _name_4 = authEntity.getName();
    String _firstUpper_2 = StringExtensions.toFirstUpper(_name_4);
    _builder.append(_firstUpper_2, "\t\t");
    _builder.append("s();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("panel.removeContent();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("panel.setContent(authForm);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public static AuthorizerController getInstance() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (controller == null) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("controller = new AuthorizerController();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("AuthorizerForm aF = new AuthorizerForm();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Registry.register(AuthorizerForm.ID, aF);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("PopUp");
    String _name_5 = authEntity.getName();
    String _firstUpper_3 = StringExtensions.toFirstUpper(_name_5);
    _builder.append(_firstUpper_3, "\t\t\t");
    _builder.append("RoleForm pURF = new PopUp");
    String _name_6 = authEntity.getName();
    String _firstUpper_4 = StringExtensions.toFirstUpper(_name_6);
    _builder.append(_firstUpper_4, "\t\t\t");
    _builder.append("RoleForm();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("Registry.register(PopUp");
    String _name_7 = authEntity.getName();
    String _firstUpper_5 = StringExtensions.toFirstUpper(_name_7);
    _builder.append(_firstUpper_5, "\t\t\t");
    _builder.append("RoleForm.ID, pURF);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("PopUpRoleForm pRF = new PopUpRoleForm();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Registry.register(PopUpRoleForm.ID, pRF);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("PopUpRoleServiceForm pRSF = new PopUpRoleServiceForm();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Registry.register(PopUpRoleServiceForm.ID, pRSF);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return controller;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public List<ServiceTO> get");
    String _name_8 = authEntity.getName();
    String _firstUpper_6 = StringExtensions.toFirstUpper(_name_8);
    _builder.append(_firstUpper_6, "\t");
    _builder.append("Services(");
    String _type = DomainCodeUtilities.getType(beId);
    _builder.append(_type, "\t");
    _builder.append(" ");
    String _name_9 = authEntity.getName();
    String _lowerCase_12 = _name_9.toLowerCase();
    _builder.append(_lowerCase_12, "\t");
    _builder.append(") {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return authManager.get");
    String _name_10 = authEntity.getName();
    String _firstUpper_7 = StringExtensions.toFirstUpper(_name_10);
    _builder.append(_firstUpper_7, "\t\t");
    _builder.append("Services(");
    String _name_11 = authEntity.getName();
    String _lowerCase_13 = _name_11.toLowerCase();
    _builder.append(_lowerCase_13, "\t\t");
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void authorize(ServiceTO service) throws Exception {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("UserTO to = Registry.get(PCSUI.USER);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<ServiceTO> ");
    String _name_12 = authEntity.getName();
    String _lowerCase_14 = _name_12.toLowerCase();
    _builder.append(_lowerCase_14, "\t\t");
    _builder.append("Services = authManager.get");
    String _name_13 = authEntity.getName();
    String _firstUpper_8 = StringExtensions.toFirstUpper(_name_13);
    _builder.append(_firstUpper_8, "\t\t");
    _builder.append("Services(to.get");
    Attribute _iD = DomainCodeUtilities.getID(authEntity);
    String _name_14 = _iD.getName();
    String _firstUpper_9 = StringExtensions.toFirstUpper(_name_14);
    _builder.append(_firstUpper_9, "\t\t");
    _builder.append("());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("if (!");
    String _name_15 = authEntity.getName();
    String _lowerCase_15 = _name_15.toLowerCase();
    _builder.append(_lowerCase_15, "\t\t");
    _builder.append("Services.contains(service))");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("throw new Exception(\"");
    String _name_16 = authEntity.getName();
    String _firstUpper_10 = StringExtensions.toFirstUpper(_name_16);
    _builder.append(_firstUpper_10, "\t\t\t");
    _builder.append(" is not authorized to perform this task\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void dataTableSheetEvent() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm aF = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int selectedTab = aF.getTsData().getTabPosition(");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("aF.getTsData().getTab(aF.getTsData().getSelectedTab()));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("switch (selectedTab) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("case 0:");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTsDetails().getTab(0).setEnabled(true);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTsDetails().getTab(1).setEnabled(false);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getButton_6().setEnabled(true);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getButton_7().setEnabled(true);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("case 1:");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTsDetails().getTab(0).setEnabled(false);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTsDetails().getTab(1).setEnabled(true);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getButton_6().setEnabled(true);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getButton_7().setEnabled(true);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("listAllRoles();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("case 2:");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTsDetails().getTab(0).setEnabled(false);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTsDetails().getTab(1).setEnabled(false);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getButton_6().setEnabled(false);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getButton_7().setEnabled(false);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("listAllServices();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private void listAll");
    String _name_17 = authEntity.getName();
    String _firstUpper_11 = StringExtensions.toFirstUpper(_name_17);
    _builder.append(_firstUpper_11, "\t");
    _builder.append("s() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    List<Contracts> _contract = DomainCodeUtilities.getContract(authEntity, ListAll.class);
    Contracts con = _contract.get(0);
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("List<");
    String _name_18 = authEntity.getName();
    String _firstUpper_12 = StringExtensions.toFirstUpper(_name_18);
    _builder.append(_firstUpper_12, "\t\t");
    _builder.append("TO> users = ");
    String _name_19 = authEntity.getName();
    String _firstUpper_13 = StringExtensions.toFirstUpper(_name_19);
    _builder.append(_firstUpper_13, "\t\t");
    _builder.append("Controller.getInstance().");
    String _name_20 = con.getName();
    _builder.append(_name_20, "\t\t");
    _builder.append("();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm aF = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("aF.getTable");
    String _name_21 = authEntity.getName();
    String _firstUpper_14 = StringExtensions.toFirstUpper(_name_21);
    _builder.append(_firstUpper_14, "\t\t");
    _builder.append("s().removeAllItems();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("for (");
    String _name_22 = authEntity.getName();
    String _firstUpper_15 = StringExtensions.toFirstUpper(_name_22);
    _builder.append(_firstUpper_15, "\t\t");
    _builder.append("TO userTO : users) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("Object data[] = { userTO.get");
    String _name_23 = beId.getName();
    String _firstUpper_16 = StringExtensions.toFirstUpper(_name_23);
    _builder.append(_firstUpper_16, "\t\t\t");
    _builder.append("(), userTO.get");
    Attribute _secondAttribute = DomainCodeUtilities.getSecondAttribute(authEntity);
    String _name_24 = _secondAttribute.getName();
    String _firstUpper_17 = StringExtensions.toFirstUpper(_name_24);
    _builder.append(_firstUpper_17, "\t\t\t");
    _builder.append("() };");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("aF.getTable");
    String _name_25 = authEntity.getName();
    String _firstUpper_18 = StringExtensions.toFirstUpper(_name_25);
    _builder.append(_firstUpper_18, "\t\t\t");
    _builder.append("s().addItem(data, userTO);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void listAllRoles() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<RoleTO> roles = authManager.getAllRoles();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm aF = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("aF.getTableRolesData().removeAllItems();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (RoleTO roleTO : roles) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Object data[] = { roleTO.getName(), roleTO.getDescription() };");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTableRolesData().addItem(data, roleTO);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void list");
    String _name_26 = authEntity.getName();
    String _firstUpper_19 = StringExtensions.toFirstUpper(_name_26);
    _builder.append(_firstUpper_19, "\t");
    _builder.append("Roles(");
    String _type_1 = DomainCodeUtilities.getType(beId);
    _builder.append(_type_1, "\t");
    _builder.append(" ");
    String _name_27 = authEntity.getName();
    String _lowerCase_16 = _name_27.toLowerCase();
    _builder.append(_lowerCase_16, "\t");
    _builder.append(") {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("List<RoleTO> roles = authManager.get");
    String _name_28 = authEntity.getName();
    String _firstUpper_20 = StringExtensions.toFirstUpper(_name_28);
    _builder.append(_firstUpper_20, "\t\t");
    _builder.append("Roles(");
    String _name_29 = authEntity.getName();
    String _lowerCase_17 = _name_29.toLowerCase();
    _builder.append(_lowerCase_17, "\t\t");
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm aF = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("aF.getTableRolesDetails().removeAllItems();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (RoleTO roleTO : roles) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Object data[] = { roleTO.getName(), roleTO.getDescription() };");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTableRolesDetails().addItem(data, roleTO);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void listRoleServices(String roleName) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<ServiceTO> services = authManager.getRoleServices(roleName);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm aF = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("aF.getTableServicesDetails().removeAllItems();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (ServiceTO serviceTO : services) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Object data[] = { serviceTO.getName(), serviceTO.getDescription() };");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTableServicesDetails().addItem(data, serviceTO);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void listAllServices() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<ServiceTO> services = authManager.getAllServices();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm aF = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("aF.getTableServicesData().removeAllItems();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (ServiceTO serviceTO : services) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Object data[] = { serviceTO.getName(), serviceTO.getDescription() };");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("aF.getTableServicesData().addItem(data, serviceTO);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void popUpRoleForm() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("PopUpRoleForm pRF = Registry.get(PopUpRoleForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("((");
    String _upperCase_3 = packageName.toUpperCase();
    _builder.append(_upperCase_3, "\t\t");
    _builder.append("UI) Registry.get(");
    String _upperCase_4 = packageName.toUpperCase();
    _builder.append(_upperCase_4, "\t\t");
    _builder.append("UI.UI)).openSubWindow(\"Role\", pRF);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void popUpAddDetailForm() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm aF = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("TabSheet tS = aF.getTsDetails();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int selectedTab = tS.getTabPosition(tS.getTab(tS.getSelectedTab()));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("switch (selectedTab) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("case TAB_");
    String _name_30 = authEntity.getName();
    String _upperCase_5 = _name_30.toUpperCase();
    _builder.append(_upperCase_5, "\t\t");
    _builder.append("S:");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    String _name_31 = authEntity.getName();
    String _firstUpper_21 = StringExtensions.toFirstUpper(_name_31);
    _builder.append(_firstUpper_21, "\t\t\t");
    _builder.append("TO user = (");
    String _name_32 = authEntity.getName();
    String _firstUpper_22 = StringExtensions.toFirstUpper(_name_32);
    _builder.append(_firstUpper_22, "\t\t\t");
    _builder.append("TO) aF.getTable");
    String _name_33 = authEntity.getName();
    String _firstUpper_23 = StringExtensions.toFirstUpper(_name_33);
    _builder.append(_firstUpper_23, "\t\t\t");
    _builder.append("s().getValue();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("if (user != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("PopUp");
    String _name_34 = authEntity.getName();
    String _firstUpper_24 = StringExtensions.toFirstUpper(_name_34);
    _builder.append(_firstUpper_24, "\t\t\t\t");
    _builder.append("RoleForm uRF = Registry.get(PopUp");
    String _name_35 = authEntity.getName();
    String _firstUpper_25 = StringExtensions.toFirstUpper(_name_35);
    _builder.append(_firstUpper_25, "\t\t\t\t");
    _builder.append("RoleForm.ID);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append("List<RoleTO> roles = authManager.getAllRoles();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("populate");
    String _name_36 = authEntity.getName();
    String _firstUpper_26 = StringExtensions.toFirstUpper(_name_36);
    _builder.append(_firstUpper_26, "\t\t\t\t");
    _builder.append("RolesCombo(roles);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append("uRF.set");
    String _name_37 = authEntity.getName();
    String _firstUpper_27 = StringExtensions.toFirstUpper(_name_37);
    _builder.append(_firstUpper_27, "\t\t\t\t");
    _builder.append("(user.get");
    String _name_38 = beId.getName();
    String _firstUpper_28 = StringExtensions.toFirstUpper(_name_38);
    _builder.append(_firstUpper_28, "\t\t\t\t");
    _builder.append("());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t");
    _builder.append("((");
    String _upperCase_6 = packageName.toUpperCase();
    _builder.append(_upperCase_6, "\t\t\t\t");
    _builder.append("UI) Registry.get(");
    String _upperCase_7 = packageName.toUpperCase();
    _builder.append(_upperCase_7, "\t\t\t\t");
    _builder.append("UI.UI)).openSubWindow(\"Role\", uRF);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("((");
    String _upperCase_8 = packageName.toUpperCase();
    _builder.append(_upperCase_8, "\t\t\t\t");
    _builder.append("UI) Registry.get(");
    String _upperCase_9 = packageName.toUpperCase();
    _builder.append(_upperCase_9, "\t\t\t\t");
    _builder.append("UI.UI)).showNotification(");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    String _upperCase_10 = packageName.toUpperCase();
    _builder.append(_upperCase_10, "\t\t\t\t\t\t");
    _builder.append("UI.MSG_ERR, \"Please select a ");
    String _name_39 = authEntity.getName();
    String _lowerCase_18 = _name_39.toLowerCase();
    _builder.append(_lowerCase_18, "\t\t\t\t\t\t");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("case TAB_ROLES:");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("RoleTO role = (RoleTO) aF.getTableRolesData().getValue();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (role != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("PopUpRoleServiceForm rSF = Registry");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".get(PopUpRoleServiceForm.ID);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("List<ServiceTO> services = authManager.getAllServices();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("populateRoleServicesCombo(services);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("rSF.setRole(role.getName());");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("((");
    String _upperCase_11 = packageName.toUpperCase();
    _builder.append(_upperCase_11, "\t\t\t\t");
    _builder.append("UI) Registry.get(");
    String _upperCase_12 = packageName.toUpperCase();
    _builder.append(_upperCase_12, "\t\t\t\t");
    _builder.append("UI.UI)).openSubWindow(\"Service\", rSF);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("((");
    String _upperCase_13 = packageName.toUpperCase();
    _builder.append(_upperCase_13, "\t\t\t\t");
    _builder.append("UI) Registry.get(");
    String _upperCase_14 = packageName.toUpperCase();
    _builder.append(_upperCase_14, "\t\t\t\t");
    _builder.append("UI.UI)).showNotification(");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    String _upperCase_15 = packageName.toUpperCase();
    _builder.append(_upperCase_15, "\t\t\t\t\t\t");
    _builder.append("UI.MSG_ERR, \"Please select a role\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("default:");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void createRole() {");
    _builder.newLine();
    _builder.append("\t\t");
    String _upperCase_16 = packageName.toUpperCase();
    _builder.append(_upperCase_16, "\t\t");
    _builder.append("UI ui = Registry.get(");
    String _upperCase_17 = packageName.toUpperCase();
    _builder.append(_upperCase_17, "\t\t");
    _builder.append("UI.UI);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("PopUpRoleForm pRF = Registry.get(PopUpRoleForm.ID);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("String name = pRF.getTextField_1().getValue();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("String description = pRF.getTextField_2().getValue();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (name != null && !name.equals(\"\") && description != null");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("&& !description.equals(\"\")) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("RoleTO role = new RoleTO();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("role.setName(name);");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("role.setDescription(description);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (authManager.createRole(role)) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_18 = packageName.toUpperCase();
    _builder.append(_upperCase_18, "\t\t\t\t\t");
    _builder.append("UI.MSG_NOT,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("\"Creation process executed successfully\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("listAllRoles();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("pRF.clearFormFields();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.closeSubWindow();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_19 = packageName.toUpperCase();
    _builder.append(_upperCase_19, "\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("\"Creation process failed\");");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("((");
    String _upperCase_20 = packageName.toUpperCase();
    _builder.append(_upperCase_20, "\t\t\t\t");
    _builder.append("UI) Registry.get(");
    String _upperCase_21 = packageName.toUpperCase();
    _builder.append(_upperCase_21, "\t\t\t\t");
    _builder.append("UI.UI))");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".showNotification(");
    String _upperCase_22 = packageName.toUpperCase();
    _builder.append(_upperCase_22, "\t\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t\t");
    _builder.append("\"Please fill in all required fields (*)\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_23 = packageName.toUpperCase();
    _builder.append(_upperCase_23, "\t\t\t");
    _builder.append("UI.MSG_ERR, e.getMessage());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void deleteRole() {");
    _builder.newLine();
    _builder.append("\t\t");
    String _upperCase_24 = packageName.toUpperCase();
    _builder.append(_upperCase_24, "\t\t");
    _builder.append("UI ui = (");
    String _upperCase_25 = packageName.toUpperCase();
    _builder.append(_upperCase_25, "\t\t");
    _builder.append("UI) Registry.get(");
    String _upperCase_26 = packageName.toUpperCase();
    _builder.append(_upperCase_26, "\t\t");
    _builder.append("UI.UI);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm aF = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("RoleTO role = (RoleTO) aF.getTableRolesData().getValue();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (role != null) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (authManager.deleteRole(role)) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_27 = packageName.toUpperCase();
    _builder.append(_upperCase_27, "\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("\"Role \'\" + role.getName() + \"\' removed sucessfully\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("listAllRoles();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_28 = packageName.toUpperCase();
    _builder.append(_upperCase_28, "\t\t\t\t\t");
    _builder.append("UI.MSG_ERR, \"Role cannot be removed\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_29 = packageName.toUpperCase();
    _builder.append(_upperCase_29, "\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("\"Role cannot be removed because it is associated to users and/or services\");");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_30 = packageName.toUpperCase();
    _builder.append(_upperCase_30, "\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("\"Please select a role to be removed\");");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void removeDetailRecord() {");
    _builder.newLine();
    _builder.append("\t\t");
    String _upperCase_31 = packageName.toUpperCase();
    _builder.append(_upperCase_31, "\t\t");
    _builder.append("UI ui = (");
    String _upperCase_32 = packageName.toUpperCase();
    _builder.append(_upperCase_32, "\t\t");
    _builder.append("UI) Registry.get(");
    String _upperCase_33 = packageName.toUpperCase();
    _builder.append(_upperCase_33, "\t\t");
    _builder.append("UI.UI);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("AuthorizerForm aF = Registry.get(AuthorizerForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("TabSheet tS = aF.getTsDetails();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int selectedTab = tS.getTabPosition(tS.getTab(tS.getSelectedTab()));");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("switch (selectedTab) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("case TAB_");
    String _name_40 = authEntity.getName();
    String _upperCase_34 = _name_40.toUpperCase();
    _builder.append(_upperCase_34, "\t\t");
    _builder.append("S:");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    String _name_41 = authEntity.getName();
    String _firstUpper_29 = StringExtensions.toFirstUpper(_name_41);
    _builder.append(_firstUpper_29, "\t\t\t");
    _builder.append("TO user = (");
    String _name_42 = authEntity.getName();
    String _firstUpper_30 = StringExtensions.toFirstUpper(_name_42);
    _builder.append(_firstUpper_30, "\t\t\t");
    _builder.append("TO) aF.getTable");
    String _name_43 = authEntity.getName();
    String _firstUpper_31 = StringExtensions.toFirstUpper(_name_43);
    _builder.append(_firstUpper_31, "\t\t\t");
    _builder.append("s().getValue();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("if (user != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("RoleTO role = (RoleTO) aF.getTableRolesDetails().getValue();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (role != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("if (authManager.removeRoleFrom");
    String _name_44 = authEntity.getName();
    String _firstUpper_32 = StringExtensions.toFirstUpper(_name_44);
    _builder.append(_firstUpper_32, "\t\t\t\t\t\t");
    _builder.append("(user, role)) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    String _upperCase_35 = packageName.toUpperCase();
    _builder.append(_upperCase_35, "\t\t\t\t\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("\"Role \'\" + role.getName()");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
    _builder.append("+ \"\' removed from ");
    String _name_45 = authEntity.getName();
    String _lowerCase_19 = _name_45.toLowerCase();
    _builder.append(_lowerCase_19, "\t\t\t\t\t\t\t\t\t\t\t");
    _builder.append(" \"");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t\t\t\t\t");
    _builder.append("+ user.get");
    String _name_46 = beId.getName();
    String _firstUpper_33 = StringExtensions.toFirstUpper(_name_46);
    _builder.append(_firstUpper_33, "\t\t\t\t\t\t\t\t\t\t\t");
    _builder.append("());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("list");
    String _name_47 = authEntity.getName();
    String _firstUpper_34 = StringExtensions.toFirstUpper(_name_47);
    _builder.append(_firstUpper_34, "\t\t\t\t\t\t\t");
    _builder.append("Roles(user.get");
    String _name_48 = beId.getName();
    String _firstUpper_35 = StringExtensions.toFirstUpper(_name_48);
    _builder.append(_firstUpper_35, "\t\t\t\t\t\t\t");
    _builder.append("());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_36 = packageName.toUpperCase();
    _builder.append(_upperCase_36, "\t\t\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("\"Role cannot be removed\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_37 = packageName.toUpperCase();
    _builder.append(_upperCase_37, "\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("\"Please select a role to be removed\");");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_38 = packageName.toUpperCase();
    _builder.append(_upperCase_38, "\t\t\t\t");
    _builder.append("UI.MSG_ERR, \"Please select a user\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("case TAB_ROLES:");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("RoleTO role = (RoleTO) aF.getTableRolesData().getValue();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (role != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("ServiceTO service = (ServiceTO) aF.getTableServicesDetails()");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append(".getValue();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (service != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("if (authManager.removeServiceFromRole(role, service)) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_39 = packageName.toUpperCase();
    _builder.append(_upperCase_39, "\t\t\t\t\t\t\t");
    _builder.append("UI.MSG_ERR, \"Service \'\"");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("+ service.getName()");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("+ \"\' removed from role \" + role.getName());");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("listRoleServices(role.getName());");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_40 = packageName.toUpperCase();
    _builder.append(_upperCase_40, "\t\t\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("\"Role cannot be removed\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("// TODO Auto-generated catch block");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("e.printStackTrace();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_41 = packageName.toUpperCase();
    _builder.append(_upperCase_41, "\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("\"Please select a service to be removed\");");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_42 = packageName.toUpperCase();
    _builder.append(_upperCase_42, "\t\t\t\t");
    _builder.append("UI.MSG_ERR, \"Please select a role\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("default:");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("break;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public boolean addRoleTo");
    String _name_49 = authEntity.getName();
    String _firstUpper_36 = StringExtensions.toFirstUpper(_name_49);
    _builder.append(_firstUpper_36, "\t");
    _builder.append("(");
    String _type_2 = DomainCodeUtilities.getType(beId);
    _builder.append(_type_2, "\t");
    _builder.append(" ");
    String _name_50 = authEntity.getName();
    String _lowerCase_20 = _name_50.toLowerCase();
    _builder.append(_lowerCase_20, "\t");
    _builder.append(") {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    String _upperCase_43 = packageName.toUpperCase();
    _builder.append(_upperCase_43, "\t\t");
    _builder.append("UI ui = Registry.get(");
    String _upperCase_44 = packageName.toUpperCase();
    _builder.append(_upperCase_44, "\t\t");
    _builder.append("UI.UI);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("PopUp");
    String _name_51 = authEntity.getName();
    String _firstUpper_37 = StringExtensions.toFirstUpper(_name_51);
    _builder.append(_firstUpper_37, "\t\t\t");
    _builder.append("RoleForm uRF = Registry.get(PopUp");
    String _name_52 = authEntity.getName();
    String _firstUpper_38 = StringExtensions.toFirstUpper(_name_52);
    _builder.append(_firstUpper_38, "\t\t\t");
    _builder.append("RoleForm.ID);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("RoleTO role = (RoleTO) uRF.getComboBox_1().getValue();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (role != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (authManager.addRoleTo");
    String _name_53 = authEntity.getName();
    String _firstUpper_39 = StringExtensions.toFirstUpper(_name_53);
    _builder.append(_firstUpper_39, "\t\t\t\t");
    _builder.append("(");
    String _name_54 = authEntity.getName();
    String _lowerCase_21 = _name_54.toLowerCase();
    _builder.append(_lowerCase_21, "\t\t\t\t");
    _builder.append(", role)) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_45 = packageName.toUpperCase();
    _builder.append(_upperCase_45, "\t\t\t\t\t");
    _builder.append("UI.MSG_NOT,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("\"Role \'\" + role.getName() + \"\' added to ");
    String _name_55 = authEntity.getName();
    String _firstUpper_40 = StringExtensions.toFirstUpper(_name_55);
    _builder.append(_firstUpper_40, "\t\t\t\t\t\t\t");
    _builder.append(" \'\"");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("+ ");
    String _name_56 = authEntity.getName();
    String _lowerCase_22 = _name_56.toLowerCase();
    _builder.append(_lowerCase_22, "\t\t\t\t\t\t\t\t\t");
    _builder.append(" + \"\'\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.closeSubWindow();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("list");
    String _name_57 = authEntity.getName();
    String _firstUpper_41 = StringExtensions.toFirstUpper(_name_57);
    _builder.append(_firstUpper_41, "\t\t\t\t\t");
    _builder.append("Roles(");
    String _name_58 = authEntity.getName();
    String _lowerCase_23 = _name_58.toLowerCase();
    _builder.append(_lowerCase_23, "\t\t\t\t\t");
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_46 = packageName.toUpperCase();
    _builder.append(_upperCase_46, "\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("\"Role cannot be added to ");
    String _name_59 = authEntity.getName();
    String _lowerCase_24 = _name_59.toLowerCase();
    _builder.append(_lowerCase_24, "\t\t\t\t\t\t\t");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_47 = packageName.toUpperCase();
    _builder.append(_upperCase_47, "\t\t\t\t");
    _builder.append("UI.MSG_ERR, \"Please select a role\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_48 = packageName.toUpperCase();
    _builder.append(_upperCase_48, "\t\t\t");
    _builder.append("UI.MSG_ERR, e.getMessage());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public boolean addServiceToRole(String roleId) {");
    _builder.newLine();
    _builder.append("\t\t");
    String _upperCase_49 = packageName.toUpperCase();
    _builder.append(_upperCase_49, "\t\t");
    _builder.append("UI ui = Registry.get(");
    String _upperCase_50 = packageName.toUpperCase();
    _builder.append(_upperCase_50, "\t\t");
    _builder.append("UI.UI);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("PopUpRoleServiceForm rSF = Registry.get(PopUpRoleServiceForm.ID);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("ServiceTO service = (ServiceTO) rSF.getComboBox_1().getValue();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (service != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (authManager.addServiceToRole(roleId, service)) {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_51 = packageName.toUpperCase();
    _builder.append(_upperCase_51, "\t\t\t\t\t");
    _builder.append("UI.MSG_NOT,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("\"Service \'\" + service.getName()");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t\t\t\t");
    _builder.append("+ \"\' added to Role \'\" + roleId + \"\'\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.closeSubWindow();");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("listRoleServices(roleId);");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("} else {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_52 = packageName.toUpperCase();
    _builder.append(_upperCase_52, "\t\t\t\t\t");
    _builder.append("UI.MSG_ERR,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t\t\t\t\t");
    _builder.append("\"Service cannot be added to role\");");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("} else");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_53 = packageName.toUpperCase();
    _builder.append(_upperCase_53, "\t\t\t\t");
    _builder.append("UI.MSG_ERR, \"Please select a service\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("} catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("ui.showNotification(");
    String _upperCase_54 = packageName.toUpperCase();
    _builder.append(_upperCase_54, "\t\t\t");
    _builder.append("UI.MSG_ERR, e.getMessage());");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private void populate");
    String _name_60 = authEntity.getName();
    String _firstUpper_42 = StringExtensions.toFirstUpper(_name_60);
    _builder.append(_firstUpper_42, "\t");
    _builder.append("RolesCombo(List<RoleTO> roles) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("PopUp");
    String _name_61 = authEntity.getName();
    String _firstUpper_43 = StringExtensions.toFirstUpper(_name_61);
    _builder.append(_firstUpper_43, "\t\t");
    _builder.append("RoleForm uRF = Registry.get(PopUp");
    String _name_62 = authEntity.getName();
    String _firstUpper_44 = StringExtensions.toFirstUpper(_name_62);
    _builder.append(_firstUpper_44, "\t\t");
    _builder.append("RoleForm.ID);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("ComboBox combo = uRF.getComboBox_1();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("combo.removeAllItems();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (RoleTO roleTO : roles) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("combo.addItem(roleTO);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private void populateRoleServicesCombo(List<ServiceTO> services) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("PopUpRoleServiceForm rSF = Registry.get(PopUpRoleServiceForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ComboBox combo = rSF.getComboBox_1();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("combo.removeAllItems();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (ServiceTO serviceTO : services) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("combo.addItem(serviceTO);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void update");
    String _name_63 = authEntity.getName();
    String _firstUpper_45 = StringExtensions.toFirstUpper(_name_63);
    _builder.append(_firstUpper_45, "\t");
    _builder.append("RolesFormFields() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("PopUp");
    String _name_64 = authEntity.getName();
    String _firstUpper_46 = StringExtensions.toFirstUpper(_name_64);
    _builder.append(_firstUpper_46, "\t\t");
    _builder.append("RoleForm uRF = Registry.get(PopUp");
    String _name_65 = authEntity.getName();
    String _firstUpper_47 = StringExtensions.toFirstUpper(_name_65);
    _builder.append(_firstUpper_47, "\t\t");
    _builder.append("RoleForm.ID);");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("ComboBox combo = uRF.getComboBox_1();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("RoleTO role = (RoleTO) combo.getValue();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("TextField tx1 = uRF.getTextField_1();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("TextField tx2 = uRF.getTextField_2();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (role != null) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("tx1.setValue(role.getName());");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("tx2.setValue(role.getDescription());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void updateRoleServicesFormFields() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("PopUpRoleServiceForm rSF = Registry.get(PopUpRoleServiceForm.ID);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ComboBox combo = rSF.getComboBox_1();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ServiceTO service = (ServiceTO) combo.getValue();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("TextField tx1 = rSF.getTextField_1();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("TextField tx2 = rSF.getTextField_2();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (service != null) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("tx1.setValue(service.getName());");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("tx2.setValue(service.getDescription());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Command getAuthCommand() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return new Command() {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("private static final long serialVersionUID = 1L;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("public void menuSelected(MenuItem selectedItem) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("showAuthForm();");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("};");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public boolean hasAdminRole(");
    String _type_3 = DomainCodeUtilities.getType(beId);
    _builder.append(_type_3, "\t");
    _builder.append(" ");
    String _name_66 = authEntity.getName();
    String _lowerCase_25 = _name_66.toLowerCase();
    _builder.append(_lowerCase_25, "\t");
    _builder.append(") {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("List<RoleTO> userRoles = authManager.get");
    String _name_67 = authEntity.getName();
    String _firstUpper_48 = StringExtensions.toFirstUpper(_name_67);
    _builder.append(_firstUpper_48, "\t\t");
    _builder.append("Roles(");
    String _name_68 = authEntity.getName();
    String _lowerCase_26 = _name_68.toLowerCase();
    _builder.append(_lowerCase_26, "\t\t");
    _builder.append(");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("RoleTO adm = new RoleTO();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("adm.setName(\"admin\");");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return userRoles.contains(adm);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void contributeProcess(Object data) throws Exception {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String serviceName = (String) data;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ServiceTO service = new ServiceTO();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("service.setName(serviceName);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("authorize(service);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
