package co.shift.templates.ejb.contributed.authenticity;

import domainmetamodel.BusinessEntity;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.StringExtensions;

@SuppressWarnings("all")
public class AuthJPATemplate {
  public static CharSequence generateRoleEntity(final String packageName, final BusinessEntity authEntity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package co.shift.");
    String _lowerCase = packageName.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".authorization.entity;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.io.Serializable;");
    _builder.newLine();
    _builder.append("import javax.persistence.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import co.shift.pcs.to.RoleTO;");
    _builder.newLine();
    _builder.append("import co.shift.pcs.to.ServiceTO;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import java.util.ArrayList;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Entity");
    _builder.newLine();
    _builder.append("@Table(name = \"Roles\")");
    _builder.newLine();
    _builder.append("@NamedQueries({ @NamedQuery(name = \"auth.get");
    String _name = authEntity.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "");
    _builder.append("Roles\", query = \"SELECT r FROM Role r, ");
    String _name_1 = authEntity.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "");
    _builder.append("Role ur WHERE r.name = ur.id.role AND ur.id.");
    String _name_2 = authEntity.getName();
    String _lowerCase_1 = _name_2.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append(" = :");
    String _name_3 = authEntity.getName();
    String _lowerCase_2 = _name_3.toLowerCase();
    _builder.append(_lowerCase_2, "");
    _builder.append("id\"),");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("@NamedQuery(name = \"auth.deleteRole\", query = \"DELETE FROM Role r WHERE r.name=:rid\"),");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@NamedQuery(name = \"auth.getAllRoles\", query = \"SELECT r FROM Role r\")})");
    _builder.newLine();
    _builder.append("public class Role implements Serializable {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static final long serialVersionUID = 1L;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Id");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String name;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String description;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// bi-directional many-to-many association to Service");
    _builder.newLine();
    _builder.append("//\t@ManyToMany(mappedBy = \"roles\")");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@ManyToMany");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JoinTable(name = \"Rights\", joinColumns = { @JoinColumn(name = \"role\") }, inverseJoinColumns = { @JoinColumn(name = \"service\") })");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private List<Service> services;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// bi-directional many-to-one association to UserRole");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@OneToMany(mappedBy = \"roleBean\", orphanRemoval = true)");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private List<");
    String _name_4 = authEntity.getName();
    String _firstUpper_2 = StringExtensions.toFirstUpper(_name_4);
    _builder.append(_firstUpper_2, "\t");
    _builder.append("Role> ");
    String _name_5 = authEntity.getName();
    String _lowerCase_3 = _name_5.toLowerCase();
    _builder.append(_lowerCase_3, "\t");
    _builder.append("Roles;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Role() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getName() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setName(String name) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.name = name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getDescription() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.description;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setDescription(String description) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.description = description;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public List<Service> getServices() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.services;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setServices(List<Service> services) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.services = services;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public List<");
    String _name_6 = authEntity.getName();
    String _firstUpper_3 = StringExtensions.toFirstUpper(_name_6);
    _builder.append(_firstUpper_3, "\t");
    _builder.append("Role> get");
    String _name_7 = authEntity.getName();
    String _firstUpper_4 = StringExtensions.toFirstUpper(_name_7);
    _builder.append(_firstUpper_4, "\t");
    _builder.append("Roles() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return this.");
    String _name_8 = authEntity.getName();
    String _lowerCase_4 = _name_8.toLowerCase();
    _builder.append(_lowerCase_4, "\t\t");
    _builder.append("Roles;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void set");
    String _name_9 = authEntity.getName();
    String _firstUpper_5 = StringExtensions.toFirstUpper(_name_9);
    _builder.append(_firstUpper_5, "\t");
    _builder.append("Roles(List<");
    String _name_10 = authEntity.getName();
    String _firstUpper_6 = StringExtensions.toFirstUpper(_name_10);
    _builder.append(_firstUpper_6, "\t");
    _builder.append("Role> ");
    String _name_11 = authEntity.getName();
    String _lowerCase_5 = _name_11.toLowerCase();
    _builder.append(_lowerCase_5, "\t");
    _builder.append("Roles) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this.");
    String _name_12 = authEntity.getName();
    String _lowerCase_6 = _name_12.toLowerCase();
    _builder.append(_lowerCase_6, "\t\t");
    _builder.append("Roles = ");
    String _name_13 = authEntity.getName();
    String _lowerCase_7 = _name_13.toLowerCase();
    _builder.append(_lowerCase_7, "\t\t");
    _builder.append("Roles;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public RoleTO toTO() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("RoleTO to = new RoleTO();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("to.setDescription(description);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("to.setName(name);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<ServiceTO> servicesTO = new ArrayList<>();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (Service service : services) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("servicesTO.add(service.toTO());");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("to.setServices(servicesTO);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return to;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public static CharSequence generateServiceEntity(final String packageName) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package co.shift.");
    String _lowerCase = packageName.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".authorization.entity;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.io.Serializable;");
    _builder.newLine();
    _builder.append("import javax.persistence.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import co.shift.pcs.to.ServiceTO;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Entity");
    _builder.newLine();
    _builder.append("@Table(name = \"Services\")");
    _builder.newLine();
    _builder.append("@NamedQueries({ @NamedQuery(name = \"auth.getAllServices\", query = \"SELECT s FROM Service s\") })");
    _builder.newLine();
    _builder.append("public class Service implements Serializable {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static final long serialVersionUID = 1L;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Id");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String name;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String description;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("// bi-directional many-to-many association to Role");
    _builder.newLine();
    _builder.append("//\t@ManyToMany");
    _builder.newLine();
    _builder.append("//\t@JoinTable(name = \"Rights\", joinColumns = { @JoinColumn(name = \"service\") }, inverseJoinColumns = { @JoinColumn(name = \"role\") })");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@ManyToMany(mappedBy = \"services\")");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private List<Role> roles;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Service() {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getName() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setName(String name) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.name = name;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getDescription() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.description;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setDescription(String description) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.description = description;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public List<Role> getRoles() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.roles;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setRoles(List<Role> roles) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.roles = roles;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public boolean equals(Object obj) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Service service = (Service) obj;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (service != null)");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return service.name.equals(name);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ServiceTO toTO() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("ServiceTO to = new ServiceTO();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("to.setDescription(description);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("to.setName(name);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return to;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public static CharSequence generateAuthRoleEntity(final String packageName, final BusinessEntity authEntity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package co.shift.");
    String _lowerCase = packageName.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".authorization.entity;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.io.Serializable;");
    _builder.newLine();
    _builder.append("import javax.persistence.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Entity");
    _builder.newLine();
    _builder.append("public class ");
    String _name = authEntity.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "");
    _builder.append("Role implements Serializable {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("private static final long serialVersionUID = 1L;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@EmbeddedId");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private ");
    String _name_1 = authEntity.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_1);
    _builder.append(_firstUpper_1, "\t");
    _builder.append("RolePK id;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("//bi-directional many-to-one association to Role");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@ManyToOne");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("@JoinColumn(name=\"role\", insertable=false, updatable=false)");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private Role roleBean;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    String _name_2 = authEntity.getName();
    String _firstUpper_2 = StringExtensions.toFirstUpper(_name_2);
    _builder.append(_firstUpper_2, "\t");
    _builder.append("Role() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    String _name_3 = authEntity.getName();
    String _firstUpper_3 = StringExtensions.toFirstUpper(_name_3);
    _builder.append(_firstUpper_3, "\t");
    _builder.append("RolePK getId() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return this.id;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setId(");
    String _name_4 = authEntity.getName();
    String _firstUpper_4 = StringExtensions.toFirstUpper(_name_4);
    _builder.append(_firstUpper_4, "\t");
    _builder.append("RolePK id) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this.id = id;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public Role getRoleBean() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.roleBean;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setRoleBean(Role roleBean) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.roleBean = roleBean;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public static CharSequence generateAuthRolePKEntity(final String packageName, final BusinessEntity authEntity) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package co.shift.");
    String _lowerCase = packageName.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.append(".authorization.entity;");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.io.Serializable;");
    _builder.newLine();
    _builder.append("import javax.persistence.*;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("@Embeddable");
    _builder.newLine();
    _builder.append("public class ");
    String _name = authEntity.getName();
    String _firstUpper = StringExtensions.toFirstUpper(_name);
    _builder.append(_firstUpper, "");
    _builder.append("RolePK implements Serializable {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("//default serial version id, required for serializable classes.");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private static final long serialVersionUID = 1L;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String ");
    String _name_1 = authEntity.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "\t");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String role;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ");
    String _name_2 = authEntity.getName();
    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_2);
    _builder.append(_firstUpper_1, "\t");
    _builder.append("RolePK() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String get");
    String _name_3 = authEntity.getName();
    String _firstUpper_2 = StringExtensions.toFirstUpper(_name_3);
    _builder.append(_firstUpper_2, "\t");
    _builder.append("() {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return this.");
    String _name_4 = authEntity.getName();
    String _lowerCase_2 = _name_4.toLowerCase();
    _builder.append(_lowerCase_2, "\t\t");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void set");
    String _name_5 = authEntity.getName();
    String _firstUpper_3 = StringExtensions.toFirstUpper(_name_5);
    _builder.append(_firstUpper_3, "\t");
    _builder.append("(String ");
    String _name_6 = authEntity.getName();
    String _lowerCase_3 = _name_6.toLowerCase();
    _builder.append(_lowerCase_3, "\t");
    _builder.append(") {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("this.");
    String _name_7 = authEntity.getName();
    String _lowerCase_4 = _name_7.toLowerCase();
    _builder.append(_lowerCase_4, "\t\t");
    _builder.append(" = ");
    String _name_8 = authEntity.getName();
    String _lowerCase_5 = _name_8.toLowerCase();
    _builder.append(_lowerCase_5, "\t\t");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getRole() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return this.role;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setRole(String role) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.role = role;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public boolean equals(Object other) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (this == other) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("return true;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (!(other instanceof ");
    String _name_9 = authEntity.getName();
    String _firstUpper_4 = StringExtensions.toFirstUpper(_name_9);
    _builder.append(_firstUpper_4, "\t\t");
    _builder.append("RolePK)) {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("return false;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    String _name_10 = authEntity.getName();
    String _firstUpper_5 = StringExtensions.toFirstUpper(_name_10);
    _builder.append(_firstUpper_5, "\t\t");
    _builder.append("RolePK castOther = (");
    String _name_11 = authEntity.getName();
    String _firstUpper_6 = StringExtensions.toFirstUpper(_name_11);
    _builder.append(_firstUpper_6, "\t\t");
    _builder.append("RolePK)other;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("return ");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("this.");
    String _name_12 = authEntity.getName();
    String _lowerCase_6 = _name_12.toLowerCase();
    _builder.append(_lowerCase_6, "\t\t\t");
    _builder.append(".equals(castOther.");
    String _name_13 = authEntity.getName();
    String _lowerCase_7 = _name_13.toLowerCase();
    _builder.append(_lowerCase_7, "\t\t\t");
    _builder.append(")");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t\t");
    _builder.append("&& this.role.equals(castOther.role);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public int hashCode() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("final int prime = 31;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int hash = 17;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("hash = hash * prime + this.");
    String _name_14 = authEntity.getName();
    String _lowerCase_8 = _name_14.toLowerCase();
    _builder.append(_lowerCase_8, "\t\t");
    _builder.append(".hashCode();");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("hash = hash * prime + this.role.hashCode();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return hash;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
