<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="guiMetamodel"
    nsURI="http://guiMetamodel/guiMetamodel" nsPrefix="guiMetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="GUI">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainView" lowerBound="1"
        eType="#//MainView" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="infoView" lowerBound="1"
        eType="#//InfoView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listView" lowerBound="1"
        eType="#//ListView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderView" lowerBound="1"
        eType="#//OrderView" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListView" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="createView" lowerBound="1"
        eType="#//CreateView" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InfoView" abstract="true" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateView" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="View" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrderView" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="InfoSingleView" eSuperTypes="#//InfoView"/>
</ecore:EPackage>
